### PR TITLE
Closes #22

### LINKED ISSUE #22: Possible bug in parseJSON function
There might be a possible bug in parseJSON function. https://github.com/pat310/google-trends-api/blob/master/src/resources/htmlParser.js#L38

1. When querying with multiple keywords, the data returned by this function is wrong and doesn't match the data returned by Google Trends call made in browser. So there's a bug in this function.
2. Why are you using Regex? I think parsing the JSON inside the function `google.visualization.Query.setResponse` is much safer and correct. This way you can easily separate the data for multiple keywords into their own array just by looping through the response once. 

I'd like to make a fix to this by rewriting the parseJSON function to use the JSON parsing idea I have in point 2. 

Would you like to accept a merge ?

### PR DESCRIPTION
**Pull request by mvpspl619**
Closes the issue 22. https://github.com/pat310/google-trends-api/issues/22

### CODE REVIEW

**Comment by mvpspl619** [comment]
@pat310 Can you help me get the code coverage report so I can which new parts of htmlParser.js are uncovered ?

**Comment by mvpspl619** [comment]
@pat310 Patrick, would please review this PR and approve if it's inline with your standards ?

**Comment by pat310** [comment]
@mvpspl619  Wow nice good job!  Also, thanks for adding the tests!  I will test everything out soon and then merge your PR.  I will need to actually make this a `major` version update because we are breaking backwards compatibility (the trend data returns results in a different format) but that is ok with me.

**Comment by mvpspl619** [comment]
@pat310 Thanks Patrick. Please keep me posted.

**Comment by Dayjo** [comment]
Good work! 👍

**Comment by mvpspl619** [comment]
@pat310 Got a chance to review ?

**Comment by pat310** [comment]
@mvpspl619 

When I run this test case:

```
googleTrends.trendData({keywords: ['OJ Simpson', 'olympics', 'swimming', 'lacrosse', 'cycling', 'diving', 'dressage']})
.then(function(trendData){
	console.log("here is the trendData", trendData);
})
.catch(function(err){
	console.log("there was an error", err);
	return err;
});
```
I get this error in htmlParser `there was an error TypeError: Cannot read property 'v' of undefined`.  The error occurs in the `parseJSON` function.  I attached a copy of the `htmlString` here
[htmlString.txt](https://github.com/pat310/google-trends-api/files/453085/htmlString.txt)

**Comment by mvpspl619** [comment]
@pat310 Fixed :) Nice catch.

**Comment by pat310** [comment]
@mvpspl619 
I don't receive the error anymore on multiple fields 👍 

But now the results aren't consistent.

For this query:
```
googleTrends.trendData({keywords: 'OJ Simpson'})
.then(function(trendData){
	console.log('some more stuff', util.inspect(trendData, {showHidden: false, depth: null}))
})
.catch(function(err){
	console.log("there was an error", err);
	return err;
});
```

I get these results:
```
some more stuff [ { query: '"oj simpson"',
    values:
     [ { date: '2004-01-01T05:00:00.000Z', value: 4 },
       { date: '2004-02-01T05:00:00.000Z', value: 3 },
       { date: '2004-03-01T05:00:00.000Z', value: 3 },
       { date: '2004-04-01T05:00:00.000Z', value: 4 },
       { date: '2004-05-01T04:00:00.000Z', value: 4 },
       { date: '2004-06-01T04:00:00.000Z', value: 7 },
       { date: '2004-07-01T04:00:00.000Z', value: 2 },
       { date: '2004-08-01T04:00:00.000Z', value: 2 },
       { date: '2004-09-01T04:00:00.000Z', value: 2 },
       { date: '2004-10-01T04:00:00.000Z', value: 4 },
       { date: '2004-11-01T05:00:00.000Z', value: 3 },
       { date: '2004-12-01T05:00:00.000Z', value: 4 },
       { date: '2005-01-01T05:00:00.000Z', value: 3 },
       { date: '2005-02-01T05:00:00.000Z', value: 3 },
       { date: '2005-03-01T05:00:00.000Z', value: 4 },
       { date: '2005-04-01T05:00:00.000Z', value: 4 },
       { date: '2005-05-01T04:00:00.000Z', value: 3 },
       { date: '2005-06-01T04:00:00.000Z', value: 4 },
       { date: '2005-07-01T04:00:00.000Z', value: 3 },
       { date: '2005-08-01T04:00:00.000Z', value: 2 },
       { date: '2005-09-01T04:00:00.000Z', value: 2 },
       { date: '2005-10-01T04:00:00.000Z', value: 4 },
       { date: '2005-11-01T05:00:00.000Z', value: 3 },
       { date: '2005-12-01T05:00:00.000Z', value: 3 },
       { date: '2006-01-01T05:00:00.000Z', value: 2 },
       { date: '2006-02-01T05:00:00.000Z', value: 3 },
       { date: '2006-03-01T05:00:00.000Z', value: 2 },
       { date: '2006-04-01T05:00:00.000Z', value: 2 },
       { date: '2006-05-01T04:00:00.000Z', value: 3 },
       { date: '2006-06-01T04:00:00.000Z', value: 3 },
       { date: '2006-07-01T04:00:00.000Z', value: 2 },
       { date: '2006-08-01T04:00:00.000Z', value: 3 },
       { date: '2006-09-01T04:00:00.000Z', value: 3 },
       { date: '2006-10-01T04:00:00.000Z', value: 3 },
       { date: '2006-11-01T05:00:00.000Z', value: 19 },
       { date: '2006-12-01T05:00:00.000Z', value: 3 },
       { date: '2007-01-01T05:00:00.000Z', value: 3 },
       { date: '2007-02-01T05:00:00.000Z', value: 3 },
       { date: '2007-03-01T05:00:00.000Z', value: 3 },
       { date: '2007-04-01T04:00:00.000Z', value: 2 },
       { date: '2007-05-01T04:00:00.000Z', value: 4 },
       { date: '2007-06-01T04:00:00.000Z', value: 4 },
       { date: '2007-07-01T04:00:00.000Z', value: 3 },
       { date: '2007-08-01T04:00:00.000Z', value: 4 },
       { date: '2007-09-01T04:00:00.000Z', value: 27 },
       { date: '2007-10-01T04:00:00.000Z', value: 5 },
       { date: '2007-11-01T04:00:00.000Z', value: 6 },
       { date: '2007-12-01T05:00:00.000Z', value: 3 },
       { date: '2008-01-01T05:00:00.000Z', value: 4 },
       { date: '2008-02-01T05:00:00.000Z', value: 3 },
       { date: '2008-03-01T05:00:00.000Z', value: 2 },
       { date: '2008-04-01T04:00:00.000Z', value: 3 },
       { date: '2008-05-01T04:00:00.000Z', value: 4 },
       { date: '2008-06-01T04:00:00.000Z', value: 2 },
       { date: '2008-07-01T04:00:00.000Z', value: 2 },
       { date: '2008-08-01T04:00:00.000Z', value: 2 },
       { date: '2008-09-01T04:00:00.000Z', value: 6 },
       { date: '2008-10-01T04:00:00.000Z', value: 17 },
       { date: '2008-11-01T04:00:00.000Z', value: 3 },
       { date: '2008-12-01T05:00:00.000Z', value: 19 },
       { date: '2009-01-01T05:00:00.000Z', value: 3 },
       { date: '2009-02-01T05:00:00.000Z', value: 2 },
       { date: '2009-03-01T05:00:00.000Z', value: 4 },
       { date: '2009-04-01T04:00:00.000Z', value: 4 },
       { date: '2009-05-01T04:00:00.000Z', value: 3 },
       { date: '2009-06-01T04:00:00.000Z', value: 4 },
       { date: '2009-07-01T04:00:00.000Z', value: 4 },
       { date: '2009-08-01T04:00:00.000Z', value: 3 },
       { date: '2009-09-01T04:00:00.000Z', value: 3 },
       { date: '2009-10-01T04:00:00.000Z', value: 3 },
       { date: '2009-11-01T04:00:00.000Z', value: 3 },
       { date: '2009-12-01T05:00:00.000Z', value: 4 },
       { date: '2010-01-01T05:00:00.000Z', value: 3 },
       { date: '2010-02-01T05:00:00.000Z', value: 3 },
       { date: '2010-03-01T05:00:00.000Z', value: 4 },
       { date: '2010-04-01T04:00:00.000Z', value: 3 },
       { date: '2010-05-01T04:00:00.000Z', value: 3 },
       { date: '2010-06-01T04:00:00.000Z', value: 4 },
       { date: '2010-07-01T04:00:00.000Z', value: 4 },
       { date: '2010-08-01T04:00:00.000Z', value: 3 },
       { date: '2010-09-01T04:00:00.000Z', value: 4 },
       { date: '2010-10-01T04:00:00.000Z', value: 4 },
       { date: '2010-11-01T04:00:00.000Z', value: 4 },
       { date: '2010-12-01T05:00:00.000Z', value: 4 },
       { date: '2011-01-01T05:00:00.000Z', value: 4 },
       { date: '2011-02-01T05:00:00.000Z', value: 6 },
       { date: '2011-03-01T05:00:00.000Z', value: 3 },
       { date: '2011-04-01T04:00:00.000Z', value: 3 },
       { date: '2011-05-01T04:00:00.000Z', value: 4 },
       { date: '2011-06-01T04:00:00.000Z', value: 9 },
       { date: '2011-07-01T04:00:00.000Z', value: 13 },
       { date: '2011-08-01T04:00:00.000Z', value: 4 },
       { date: '2011-09-01T04:00:00.000Z', value: 4 },
       { date: '2011-10-01T04:00:00.000Z', value: 5 },
       { date: '2011-11-01T04:00:00.000Z', value: 5 },
       { date: '2011-12-01T05:00:00.000Z', value: 4 },
       { date: '2012-01-01T05:00:00.000Z', value: 8 },
       { date: '2012-02-01T05:00:00.000Z', value: 4 },
       { date: '2012-03-01T05:00:00.000Z', value: 4 },
       { date: '2012-04-01T04:00:00.000Z', value: 5 },
       ... 53 more items ] } ]
```

And for this query:
```
googleTrends.trendData({keywords: ['OJ Simpson', 'olympics']})
.then(function(trendData){
	console.log('some more stuff', util.inspect(trendData, {showHidden: false, depth: null}))
})
.catch(function(err){
	console.log("there was an error", err);
	return err;
});
```
I get these results for `Oj Simpson`:
```
some more stuff [ { query: 'oj simpson',
    values:
     [ { date: '2004-01-01T05:00:00.000Z', value: 0 },
       { date: '2004-02-01T05:00:00.000Z', value: 0 },
       { date: '2004-03-01T05:00:00.000Z', value: 0 },
       { date: '2004-04-01T05:00:00.000Z', value: 0 },
       { date: '2004-05-01T04:00:00.000Z', value: 0 },
       { date: '2004-06-01T04:00:00.000Z', value: 0 },
       { date: '2004-07-01T04:00:00.000Z', value: 0 },
       { date: '2004-08-01T04:00:00.000Z', value: 0 },
       { date: '2004-09-01T04:00:00.000Z', value: 0 },
       { date: '2004-10-01T04:00:00.000Z', value: 0 },
       { date: '2004-11-01T05:00:00.000Z', value: 0 },
       { date: '2004-12-01T05:00:00.000Z', value: 0 },
       { date: '2005-01-01T05:00:00.000Z', value: 0 },
       { date: '2005-02-01T05:00:00.000Z', value: 0 },
       { date: '2005-03-01T05:00:00.000Z', value: 0 },
       { date: '2005-04-01T05:00:00.000Z', value: 0 },
       { date: '2005-05-01T04:00:00.000Z', value: 0 },
       { date: '2005-06-01T04:00:00.000Z', value: 0 },
       { date: '2005-07-01T04:00:00.000Z', value: 0 },
       { date: '2005-08-01T04:00:00.000Z', value: 0 },
       { date: '2005-09-01T04:00:00.000Z', value: 0 },
       { date: '2005-10-01T04:00:00.000Z', value: 0 },
       { date: '2005-11-01T05:00:00.000Z', value: 0 },
       { date: '2005-12-01T05:00:00.000Z', value: 0 },
       { date: '2006-01-01T05:00:00.000Z', value: 0 },
       { date: '2006-02-01T05:00:00.000Z', value: 0 },
       { date: '2006-03-01T05:00:00.000Z', value: 0 },
       { date: '2006-04-01T05:00:00.000Z', value: 0 },
       { date: '2006-05-01T04:00:00.000Z', value: 0 },
       { date: '2006-06-01T04:00:00.000Z', value: 0 },
       { date: '2006-07-01T04:00:00.000Z', value: 0 },
       { date: '2006-08-01T04:00:00.000Z', value: 0 },
       { date: '2006-09-01T04:00:00.000Z', value: 0 },
       { date: '2006-10-01T04:00:00.000Z', value: 0 },
       { date: '2006-11-01T05:00:00.000Z', value: 1 },
       { date: '2006-12-01T05:00:00.000Z', value: 0 },
       { date: '2007-01-01T05:00:00.000Z', value: 0 },
       { date: '2007-02-01T05:00:00.000Z', value: 0 },
       { date: '2007-03-01T05:00:00.000Z', value: 0 },
       { date: '2007-04-01T04:00:00.000Z', value: 0 },
       { date: '2007-05-01T04:00:00.000Z', value: 0 },
       { date: '2007-06-01T04:00:00.000Z', value: 0 },
       { date: '2007-07-01T04:00:00.000Z', value: 0 },
       { date: '2007-08-01T04:00:00.000Z', value: 0 },
       { date: '2007-09-01T04:00:00.000Z', value: 1 },
       { date: '2007-10-01T04:00:00.000Z', value: 0 },
       { date: '2007-11-01T04:00:00.000Z', value: 0 },
       { date: '2007-12-01T05:00:00.000Z', value: 0 },
       { date: '2008-01-01T05:00:00.000Z', value: 0 },
       { date: '2008-02-01T05:00:00.000Z', value: 0 },
       { date: '2008-03-01T05:00:00.000Z', value: 0 },
       { date: '2008-04-01T04:00:00.000Z', value: 0 },
       { date: '2008-05-01T04:00:00.000Z', value: 0 },
       { date: '2008-06-01T04:00:00.000Z', value: 0 },
       { date: '2008-07-01T04:00:00.000Z', value: 0 },
       { date: '2008-08-01T04:00:00.000Z', value: 0 },
       { date: '2008-09-01T04:00:00.000Z', value: 0 },
       { date: '2008-10-01T04:00:00.000Z', value: 1 },
       { date: '2008-11-01T04:00:00.000Z', value: 0 },
       { date: '2008-12-01T05:00:00.000Z', value: 1 },
       { date: '2009-01-01T05:00:00.000Z', value: 0 },
       { date: '2009-02-01T05:00:00.000Z', value: 0 },
       { date: '2009-03-01T05:00:00.000Z', value: 0 },
       { date: '2009-04-01T04:00:00.000Z', value: 0 },
       { date: '2009-05-01T04:00:00.000Z', value: 0 },
       { date: '2009-06-01T04:00:00.000Z', value: 0 },
       { date: '2009-07-01T04:00:00.000Z', value: 0 },
       { date: '2009-08-01T04:00:00.000Z', value: 0 },
       { date: '2009-09-01T04:00:00.000Z', value: 0 },
       { date: '2009-10-01T04:00:00.000Z', value: 0 },
       { date: '2009-11-01T04:00:00.000Z', value: 0 },
       { date: '2009-12-01T05:00:00.000Z', value: 0 },
       { date: '2010-01-01T05:00:00.000Z', value: 0 },
       { date: '2010-02-01T05:00:00.000Z', value: 0 },
       { date: '2010-03-01T05:00:00.000Z', value: 0 },
       { date: '2010-04-01T04:00:00.000Z', value: 0 },
       { date: '2010-05-01T04:00:00.000Z', value: 0 },
       { date: '2010-06-01T04:00:00.000Z', value: 0 },
       { date: '2010-07-01T04:00:00.000Z', value: 0 },
       { date: '2010-08-01T04:00:00.000Z', value: 0 },
       { date: '2010-09-01T04:00:00.000Z', value: 0 },
       { date: '2010-10-01T04:00:00.000Z', value: 0 },
       { date: '2010-11-01T04:00:00.000Z', value: 0 },
       { date: '2010-12-01T05:00:00.000Z', value: 0 },
       { date: '2011-01-01T05:00:00.000Z', value: 0 },
       { date: '2011-02-01T05:00:00.000Z', value: 0 },
       { date: '2011-03-01T05:00:00.000Z', value: 0 },
       { date: '2011-04-01T04:00:00.000Z', value: 0 },
       { date: '2011-05-01T04:00:00.000Z', value: 0 },
       { date: '2011-06-01T04:00:00.000Z', value: 0 },
       { date: '2011-07-01T04:00:00.000Z', value: 1 },
       { date: '2011-08-01T04:00:00.000Z', value: 0 },
       { date: '2011-09-01T04:00:00.000Z', value: 0 },
       { date: '2011-10-01T04:00:00.000Z', value: 0 },
       { date: '2011-11-01T04:00:00.000Z', value: 0 },
       { date: '2011-12-01T05:00:00.000Z', value: 0 },
       { date: '2012-01-01T05:00:00.000Z', value: 0 },
       { date: '2012-02-01T05:00:00.000Z', value: 0 },
       { date: '2012-03-01T05:00:00.000Z', value: 0 },
       { date: '2012-04-01T04:00:00.000Z', value: 0 },
       ... 53 more items ] },
```

Probably something I broke in PR #21 , but figured while you're fixing this method you could take a look 😛 

Also, I think we should keep the `lib` directory in the `.gitignore` since this directory is simply transpiled and built each time unless you have a compelling argument otherwise?  On a side note, I'm debating adding stage-0 support for ES7

**Comment by mvpspl619** [comment]
@pat310 I had this issue about data inconsistency before, I remember fixing it. But I'll take a look again when I get a chance. 

Let's `.gitignore` the `lib` directory. Regarding ES7 support, I'd say let's perfect the library and then work on these additions. What say ?

**Comment by pat310** [comment]
@mvpspl619 Have you had any time to look at this?

**Pull request merged**
